services:
  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      restart: unless-stopped
      volumes:
        - ./data/prometheus/config:/etc/prometheus
      command:
        - "--config.file=/etc/prometheus/prometheus.yaml"
      ports: 
        - "9090:9090"
      expose:
        - "9090"
  grafana:
      image: grafana/grafana-oss:8.5.2
      pull_policy: always
      container_name: grafana
      restart: unless-stopped
      links:
        - prometheus:prometheus
      volumes:
        - ./data/grafana:/var/lib/grafana
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin
        - GF_SERVER_DOMAIN=localhost
      ports:
        - "3000:3000"
      expose:
          - "3000"
